# Makefile for less
#
# Target:   OS/2 or compatible
# Compiler: EMX 0.9d with GCC 2.8.1

##### Start configuration section #####

# Compiler executable name
CC = gcc

# Path to system headers
INCDIR = C:\EMX\INCLUDE

# CFLAGS are compile-time options and LDFLAGS are link-time options. They are
# customized for EMX 0.9d with GCC 2.8.1. If you have a different version of the
# compiler, you may need to change some of the options to their equivalents.
#
# CFLAGS
# -Zomf     Link using OS/2 Linear Executable Linker (LINK386)
# -Wall     Enable most compiler warnings
# -O2       Optimize at level 2 (default: none)
CFLAGS = -Zomf -Wall -O2
#
# LDFLAGS
# -Zomf     Link using OS/2 Linear Executable Linker (LINK386)
# -Zcrtdll  Dynamically link the EMX Unix emulation layer & C runtime
#           Use -Zsys to statically link everything (no EMX dependency)
# -s        Remove symbol table and relocation information
LDFLAGS = -Zomf -Zcrtdll -s

# System libraries to link against
# - termcap     Terminal capabilities
LIBS = -ltermcap

##### End configuration section #####

# Add ".obj" extension to the suffix list
.SUFFIXES: .obj

# All object files to build
OBJ = \
	main.obj \
	brac.obj \
	ch.obj \
	charset.obj \
	cmdbuf.obj \
	command.obj \
	cvt.obj \
	decode.obj \
	edit.obj \
	evar.obj \
	filename.obj \
	forwback.obj \
	help.obj \
	ifile.obj \
	input.obj \
	jump.obj \
	lesskey_parse.obj \
	line.obj \
	linenum.obj \
	lmsg.obj \
	lsystem.obj \
	mark.obj \
	optfunc.obj \
	option.obj \
	opttbl.obj \
	os.obj \
	output.obj \
	pattern.obj \
	position.obj \
	prompt.obj \
	regexp.obj \
	screen.obj \
	search.obj \
	signal.obj \
	tags.obj \
	ttyin.obj \
	version.obj \
	xbuf.obj

all: less.exe scrsize.exe

less.exe: ${OBJ} less.def
	${CC} ${OBJ} less.def -o $@ ${LDFLAGS} ${LIBS}

scrsize.exe: scrsize.c
	${CC} ${CFLAGS} -Zmtd -lX11 -D__ST_MT_ERRNO__ -s $<

clean:
	-del *.exe *.obj 2> NUL

# Suffix rule associating each source file to object file
.c.obj:
	${CC} -c -I. -I$(INCDIR) ${CFLAGS} $<

defines.h: defines.o2
	-del defines.h 2> NUL
	copy defines.o2 defines.h > NUL

less.def: less.def.o2
	copy less.def.o2 less.def > NUL

# Rebuild object files when any of these change
$(OBJ): less.h defines.h funcs.h lang.h lmsg.h pattern.h xbuf.h lessmsg.inc
