# Makefile for less
#
# Target:   MS-DOS or compatible
# Compiler: Microsoft Visual C++ 1.52c
#
# Build requirements
# 1. Microsoft Visual C++ 1.52c is the last release to support building for an
#    MS-DOS target. Older versions may work but have not been tested. This
#    software is abandonware and can be obtained from various online archives
#    (e.g. archive.org).
# 2. The compiler requires a Windows system: at least Windows 3.1 or Windows NT
#    3.1 (inc. Windows 9x). I'm unsure if it works on modern Windows releases
#    (e.g. Windows 10). It's unlikely to work on any 64-bit release of Windows
#    as they have dropped 16-bit support.
# 3. When installing you can simply perform a "Typical Installation". If you
#    want to perform a "Custom Installation" you will minimally need:
#    - Microsoft C/C++ Compiler
#    - Run-time Libraries
#      - Memory Models: Large/Huge
#      - Targets: MS-DOS .EXE Files
#      - Math Support: Emulation
#
# Build steps
# 1. Open a command prompt and run "C:\MSVC\BIN\MSVCVARS.BAT" (default install
#    path) to setup the development environment.
# 2. Change to the directory with the less source and copy this Makefile to
#    "Makefile". If MSVC is not installed at "C:\MSVC" update the "INCDIR" and
#    "LIBDIR" variables appropriately.
# 3. Run "nmake". If all goes well, you'll now have a "less.exe" executable.
#    It's self-contained and can be simply copied to any other DOS system.

##### Start configuration section #####

# Compiler executable name
CC = cl

# Path to system headers
INCDIR = C:\MSVC\INCLUDE
# Path to system libraries
LIBDIR = C:\MSVC\LIB

# CFLAGS are compile-time options and LDFLAGS are link-time options. They are
# customized for MSVC 1.52 (MSC 8.00). If you have a different version of the
# compiler, you may need to change some of the options to their equivalents.
#
# CFLAGS
# /AL       Large memory model (default: small)
# /Ot       Optimize binary for speed (default: none)
# /G3       Use 386 instructions (default: 8086)
#           Reduces binary size but safe to remove if target is pre-386
# /Gt16     Allocate static data >= 16 bytes in a far segment (default: 256)
# /nologo   Suppress compiler copyright message
CFLAGS = /AL /Ot /G3 /Gt16 /nologo
#
# LDFLAGS
# /EXEPACK          Compress the image (decompress at runtime via a small stub)
# /FARCALLTRANS     Optimize far calls to procedures in the caller's segment
# /NOEXTDICTIONARY  Don't search extended dictionaries during symbol resolution
#                   Required with TXTONLY.OBJ to avoid pulling in GRAPHICS.LIB
# /STACK:0x8000     Use a 32KB stack size (default: 2KB)
# /ONERROR:NOEXE    Skip writing executable on error
# /NOLOGO           Suppress linker copyright message
LDFLAGS = /EXEPACK /FARCALLTRANS /NOEXTDICTIONARY /STACK:0x8000 /ONERROR:NOEXE /NOLOGO

# System libraries to link against
# - LLIBCE      Large memory model (L), C runtime (LIBC), 8087 emulator (E)
# - TXTONLY     Graphics library function stubs (not needed for text-mode)
LIBS = $(LIBDIR)\TXTONLY.OBJ $(LIBDIR)\LLIBCE.LIB

##### End configuration section #####

# Add ".obj" extension to the suffix list
.SUFFIXES: .obj

# All object files to build
OBJ = \
	main.obj \
	brac.obj \
	ch.obj \
	charset.obj \
	cmdbuf.obj \
	command.obj \
	cvt.obj \
	decode.obj \
	edit.obj \
	evar.obj \
	filename.obj \
	forwback.obj \
	help.obj \
	ifile.obj \
	input.obj \
	jump.obj \
	lesskey_parse.obj \
	line.obj \
	linenum.obj \
	lmsg.obj \
	lsystem.obj \
	mark.obj \
	optfunc.obj \
	option.obj \
	opttbl.obj \
	os.obj \
	output.obj \
	pattern.obj \
	position.obj \
	prompt.obj \
	screen.obj \
	search.obj \
	signal.obj \
	tags.obj \
	ttyin.obj \
	version.obj \
	xbuf.obj

all: less.exe

less.exe: $(OBJ)
	$(CC) -o $@ *.obj $(LIBS) /link $(LDFLAGS)

clean:
	-del *.exe *.obj 2> NUL

# Suffix rule associating each source file to object file
.c.obj:
	$(CC) -c -I. -I$(INCDIR) $(CFLAGS) $<

defines.h: defines.ds
	-del defines.h 2> NUL
	copy defines.ds defines.h > NUL

# Rebuild object files when any of these change
$(OBJ): less.h defines.h funcs.h lang.h lmsg.h pattern.h xbuf.h lessmsg.inc
