#!/bin/sh

echo "/* This file was generated by $0 from less.hlp at $(LC_ALL=C date -u) */"
echo '#include "less.h"'
echo
echo 'constant char helpdata[] = {'

od -b -v -A n |  # octal values, typically 16 per line
	awk '{ for(i=1; i<=NF; i++) printf("0%s,", $i); print "" }'

echo '0 };'
echo
echo 'constant int size_helpdata = sizeof(helpdata) - 1;'
