#!/usr/bin/env python

from time import gmtime

time = gmtime()
with open('less.c', 'w', newline='') as out, open('less.hlp') as infile:
    out.write("/* This file was generated by mkhelp.py from less.hlp at "
              "%d:%02d on %d/%d/%d */\n" %
              (time.tm_hour, time.tm_min, time.tm_year, time.tm_mon,
               time.tm_mday))
    out.write("#include \"less.h\"\n")
    out.write("constant char helpdata[] = {\n")
    for i, line in enumerate(infile):
        for ch in line:
            if ch == "'":
                out.write("'\\'',")
            elif ch == "\\":
                out.write("'\\\\',")
            elif ch == "\b":
                out.write("'\\b',")
            elif ch == "\t":
                out.write("'\\t',")
            elif ch == "\n":
                if (ch == line[0] and i == 0) or (len(line) > 1):
                    out.write("'\\n',\n")
            else:
                if (ord(ch) >= ord(' ')) and (ord(ch) < 0x7f):
                    out.write(f"'{ch}',")
                else:
                    out.write("0x%02x," % ord(ch))
    out.write(" 0 };\n")
    out.write("constant int size_helpdata = sizeof(helpdata) - 1;\n")
