#!/usr/bin/perl
use strict;

# Create a test file.
my $usage = "usage: maketest [-o lt-file] [-l less.exe] [-s lt_screen] [-t lesstest] [-w width] [-h height] [-O lesstest-opts] textfile\n";

use Getopt::Std;

exit main();
sub main {
	my %opt;
	die $usage if not getopts('h:l:o:O:s:t:w:', \%opt);
	my $textfile = shift @ARGV;
	die $usage if not defined $textfile;
	my $lesstest  = ($opt{t} or "./lesstest");
	my $lt_screen = ($opt{s} or "./lt_screen");
	my $less      = ($opt{l} or "../obj/less");
	my $lines     = ($opt{h} or $ENV{LINES}-1);
	my $columns   = ($opt{w} or $ENV{COLUMNS}-1);
	my $lt_opts   = ($opt{O} or "");
	$lt_opts = "-$lt_opts" if $lt_opts =~ /^[^-]/;
	my $ltfile    = $opt{o};
	if (not defined $ltfile) {
		for (my $i = 0;; ++$i) {
			my $suffix = $i ? $i : "";
			$ltfile = "lt/$textfile$suffix.lt";
			last if not -e $ltfile;
		}
	}
	my $cmd = "LINES=$lines COLUMNS=$columns $lesstest $lt_opts -o '$ltfile' -- $less '$textfile'";
	my $err = system($cmd);
	if ($err) {
		unlink $ltfile;
	} else {
		print "created $ltfile\n";
	}
	exit $err;
}
